import { Inter } from "next/font/google";

import type { Metadata } from "next";

import "../styles/globals.css";
import "@gespenst/ui/dist/style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create turbo",
  title: "Create Turborepo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html className="dark" lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
